<?php

declare(strict_types=1);

namespace PHPOS\Utility;

use PHPOS\OS\CodeInterface;
use PHPOS\Service\Component\Formatter;

class AutomaticallyGeneratedFileSignature
{
    public static function createHeader(string $commentType = '#'): string
    {
        return <<< __HEADER__
        {$commentType}
        {$commentType}                                  _     _          __             _____  _    _ _____         ____   _____
        {$commentType}     /\                          | |   | |        / _|           |  __ \| |  | |  __ \       / __ \ / ____|
        {$commentType}    /  \   ___ ___  ___ _ __ ___ | |__ | |_   _  | |_ ___  _ __  | |__) | |__| | |__) |_____| |  | | (___
        {$commentType}   / /\ \ / __/ __|/ _ \ '_ ` _ \| '_ \| | | | | |  _/ _ \| '__| |  ___/|  __  |  ___/______| |  | |\___ \
        {$commentType}  / ____ \\__ \__ \  __/ | | | | | |_) | | |_| | | || (_) | |    | |    | |  | | |          | |__| |____) |
        {$commentType} /_/    \_\___/___/\___|_| |_| |_|_.__/|_|\__, | |_| \___/|_|    |_|    |_|  |_|_|           \____/|_____/
        {$commentType}                                           __/ |
        {$commentType}                                          |___/
        {$commentType}
        {$commentType} Notice: This file is automatically generated by PHP-OS.
        {$commentType}         Do not edit this file. We cannot be held responsible if this is edited and overwritten again.
        {$commentType}


        __HEADER__;
    }
}
