<?php

declare(strict_types=1);

namespace PHPOS\Utility;

use PHPOS\OS\CodeInterface;
use PHPOS\Service\Component\Formatter;

class AutomaticallyGeneratedFileSignature
{
    public static function createHeader(string $commentType = '#'): string
    {
        return <<< __HEADER__
        {$commentType}
        {$commentType}   _______  ____  ____  _______            ___     ______
        {$commentType}  |_   __ \|_   ||   _||_   __ \         .'   `. .' ____ \
        {$commentType}    | |__) | | |__| |    | |__) |______ /  .-.  \| (___ \_|
        {$commentType}    |  ___/  |  __  |    |  ___/|______|| |   | | _.____`.
        {$commentType}   _| |_    _| |  | |_  _| |_           \  `-'  /| \____) |
        {$commentType}  |_____|  |____||____||_____|           `.___.'  \______.'
        {$commentType}
        {$commentType} Notice: This file is automatically generated by PHP-OS.
        {$commentType}         Do not edit this file. We cannot be held responsible if this is edited and overwritten again.
        {$commentType}


        __HEADER__;
    }
}
