<?php

declare(strict_types=1);

namespace PHPOS\Assembly\Processor;

use PHPOS\Architecture\Support\Hex;
use PHPOS\OS\CodeInterface;
use PHPOS\OS\DefineInterface;
use PHPOS\Runtime\KeyValue;
use PHPOS\Service\BIOS\Standard\DefineBitSize;
use PHPOS\Service\BIOS\Standard\DefineOrigin;
use PHPOS\Service\BIOS\Standard\Variable;
use PHPOS\Service\ServiceInterface;

class Readable implements ProcessorInterface
{
    public function __construct(protected CodeInterface $code, protected array $services = [], protected array $postServices = [])
    {
    }

    public function process(): string
    {
        $assembly = '';

        foreach ($this->createServices() as [$service, $parameters]) {
            $service = new $service($this->code, null, ...$parameters);

            assert($service instanceof ServiceInterface);
            $assembly .= $service->process()->assemble() . "\n";
        }

        $definitions = '';
        /**
         * @var DefineInterface $value
         */
        foreach ($this->code->architecture()->runtime()->definedDefinitions() as $value) {
            $definitions .= sprintf(
                "%%define %s %s" . "\n",
                $value->name(),
                $value->value() ?? '(null)',
            );
        }

        $assembly = $definitions . "\n" . $assembly;

        /**
         * @var KeyValue $value
         */
        foreach ($this->code->architecture()->runtime()->definedVariables() as $value) {
            $assembly .= (new Variable(
                $this->code,
                null,
                $value,
            ))->process()->assemble() . "\n";
        }

        foreach ($this->postServices as [$service, $parameters]) {
            $service = new $service($this->code, null, ...$parameters);

            assert($service instanceof ServiceInterface);
            $assembly .= $service->process()->assemble() . "\n";
        }

        return $this->createHeader() . $assembly;
    }

    private function createServices(): array
    {
        return [
            [DefineBitSize::class, [$this->code->bits()]],
            [DefineOrigin::class, [$this->code->origin()]],
            ...$this->services,
        ];
    }

    private function createHeader(): string
    {
        return <<< __HEADER__
        ;
        ;                                  _     _          __             _____  _    _ _____         ____   _____
        ;     /\                          | |   | |        / _|           |  __ \| |  | |  __ \       / __ \ / ____|
        ;    /  \   ___ ___  ___ _ __ ___ | |__ | |_   _  | |_ ___  _ __  | |__) | |__| | |__) |_____| |  | | (___
        ;   / /\ \ / __/ __|/ _ \ '_ ` _ \| '_ \| | | | | |  _/ _ \| '__| |  ___/|  __  |  ___/______| |  | |\___ \
        ;  / ____ \\__ \__ \  __/ | | | | | |_) | | |_| | | || (_) | |    | |    | |  | | |          | |__| |____) |
        ; /_/    \_\___/___/\___|_| |_| |_|_.__/|_|\__, | |_| \___/|_|    |_|    |_|  |_|_|           \____/|_____/
        ;                                           __/ |
        ;                                          |___/
        ;
        ; Notice: This file is automatically generated by PHP-OS.
        ;         Do not edit this file. We cannot be held responsible if this is edited and overwritten again.
        ;


        __HEADER__;
    }
}
